"""
@author: RK
@title: RK Pix
@nickname: rk-pix
@description: A collection of custom nodes for image processing, utilities, and creative effects.
"""

from .image_nodes import IMAGE_CLASS_MAPPINGS, IMAGE_NAME_MAPPINGS
from .utility_nodes import UTILITY_CLASS_MAPPINGS, UTILITY_NAME_MAPPINGS
from .effect_nodes import EFFECT_CLASS_MAPPINGS, EFFECT_NAME_MAPPINGS
from .video_nodes import VIDEO_CLASS_MAPPINGS, VIDEO_NAME_MAPPINGS, WEB_DIRECTORY

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(IMAGE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(UTILITY_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(UTILITY_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(EFFECT_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(EFFECT_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(VIDEO_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
